[paths]
ymldb = "data/ymldb"
grids = "data/grids"
grids_common = "data/grids/common"
operator_cards = "data/operator_cards"
theory_cards = "data/theory_cards"
opcard_template = "data/operator_cards/_template.yaml"
ekos = "data/ekos"
fktables = "data/fktables"
