name: benchmarks

on: push

jobs:
  bench:
    name: Benchmarks
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/n3pdf/bench-evol:latest
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2
        with:
          # tags needed for dynamic versioning
          fetch-depth: 0
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: false
          installer-parallel: true
      - name: Install version management tool
        run: |
          # same poetry env
          PIP="$(head -n1 $(which poetry) | cut -c 3-) -m pip"
          ${PIP} install poetry-dynamic-versioning
      - name: Install dependencies
        run: poetry install --no-interaction --no-root --with test ${{ inputs.poetry-extras }}
      - name: Install project
        run: poetry install --no-interaction
      - name: Install task runner
        run: pip install poethepoet
      - name: Lint with pylint
        run: |
          # Search for actual errors
          poe lint
          # For warnings instead return always zero
          poe lint-warnings
      - name: Get data files
        id: cache-data-files
        uses: actions/cache@v3
        with:
          path: data_files
          key: data_files-v2
      - name: Download data files
        if: steps.cache-data_files.outputs.cache-hit != 'true'
        run: |
          wget -r -np -nH --cut-dirs=1 -l 4  -e robots=off --no-verbose -P benchmarks -R index.* https://data.nnpdf.science/pineko/data_files/
          wget -r -np -nH --cut-dirs=1 -l 4  -e robots=off --no-verbose -P benchmarks -R index.* https://data.nnpdf.science/pineko/fakepdfs/
      - name: Test with pytest
        run: |
          poe bench
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage.xml
          flags: bench
          name: codecov-umbrella
          fail_ci_if_error: true
