name: tests

on: push

jobs:
  py37:
    uses: N3PDF/workflows/.github/workflows/python-poetry-tests.yml@main
    with:
      python-version: "3.7"

  py38:
    uses: N3PDF/workflows/.github/workflows/python-poetry-tests.yml@main
    with:
      python-version: "3.8"

  py39:
    uses: N3PDF/workflows/.github/workflows/python-poetry-tests.yml@main
    with:
      python-version: "3.9"

  py310:
    uses: N3PDF/workflows/.github/workflows/python-poetry-tests.yml@main
    with:
      python-version: "3.10"

steps:
- uses: actions/checkout@main
- uses: codecov/codecov-action@v2
  with:
    files: ./coverage1.xml,./coverage2.xml # optional
    flags: unittests # optional
    name: codecov-umbrella # optional
    fail_ci_if_error: true # optional (default = false)
    verbose: true # optional (default = false)
