name: Codecov
on: [push]
jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    env:
      OS: ${{ matrix.os }}
      PYTHON: '3.9'
    steps:
      - uses: actions/checkout@v2
        with:
          # tags needed for dynamic versioning
          fetch-depth: 0
      - name: Install and configure Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          # update path for this and the other steps
          export PATH=$HOME/.local/bin:$PATH
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          # prevent poetry environments
          # in order to access container pre-installed packages
          poetry config virtualenvs.create false
          # log all configurations
          poetry config --list
      - name: Install version management tool
        run: |
          # same poetry env
          PIP="$(head -n1 $(which poetry) | cut -c 3-) -m pip"
          ${PIP} install poetry-dynamic-versioning
      - name: Install project
        run: |
          poetry install --no-interaction
      - name: Run tests
        run: |
          poetry run pytest
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
          
# Reference docs at:
# https://docs.codecov.io/docs/codecovyml-reference

codecov:
  require_ci_to_pass: yes
coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        # check only master and branches that should be merged directly into
        # master
        branches:
          - main
          - develop
          - "feature/*"
          - "release/*"
          - "change_readme"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no
  # comments in the pull request are not preventing the merge, and can be
  # useful to detect dropping in unit and regression tests since they are
  # individually reported [so keep the following option commented]
  #branches:
  #- main
  #- "feature/*"
  #- "release/*"

github_checks:
  annotations: false